spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}AQB5pETTMpIMnbUlTa4b/AX+T14HXT0O2ByCN2kkG9Ntgz8qmdUnwQaZAgEVZUS+7EPM9HFenIXSDaXSDD5slkRHpVBSoOJSZuWPbbvsmgwRbzKuNui8bCiWQAm1Paosx+/fon3/MxbwOC3bGgxibGIUsimPimeGcM3U62dOmQY76epLduJgm4PMl1l+uGsOOe7mcBS3T6WKKWwxBgAyIRkEjd+V9qltXFWHWYYaC3xtSJrSngNFrkMLod7LHYS5Cd8cLCmOzy62b6eCHhp5IK+p6hjtmp4emf2az0ZZh97FJ8Kpr0Z6ywg87SbwqJZqbvT9Op7WEUTLpcsK+43aXdNSWDmHrCglLHRy2EL6e4kDL1SnhieTJqM99qzR8VKfx1I='
